version: '2.1'

services:
  sscs-case-loader:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/reform/sscs-case-loader
    container_name: sscs-case-loader
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - GAPS2_SFTP_HOST=sftp-dev-server
      - GAPS2_SFTP_USER=sftp
      - GAPS2_KEY_LOCATION=/home/webapp/sscs-sftp-key
      - GAPS2_SFTP_DIR=/incoming
      - GAPS2_DATA_DIR=/var/tmp/gaps2
      - GAPS2_ARCHIVE_DIR=/var/tmp/gaps2archive
      - GAPS2_VALID_DIR=/var/tmp/valid
      - GAPS2_SCHEMA_VALIDATION_FAILED_DIR=/var/tmp/schemaValidationFailed
      - http_proxy=
      - https_proxy=
      - no_proxy=
    depends_on:
      gaps2-sftp:
        condition: service_healthy
    links:
      - gaps2-sftp
    ports:
      # check .env
      - $SERVER_PORT:$SERVER_PORT
      
  gaps2-sftp:
    image: docker.artifactory.reform.hmcts.net/sscs/sscs-sftp:${SSCS_TESTS_VERSION:-latest}
    container_name: sscs-sftp
    command: sftp:pass:1001
    healthcheck:
      retries: 40
    ports:
      - "2222:22"
    volumes:
      - ./docker/sftp/data/incoming:/home/sftp/incoming
