version: '2.1'

services:
  gaps2-sftp:
    image: hmcts/sscs-sftp
    container_name: sscs-sftp
    command: sftp:pass:1001
    healthcheck:
      retries: 40
    ports:
      - "2222:22"
    volumes:
      - ./docker/sftp/data/incoming:/home/sftp/incoming
