---
version: '3'

services:
  ccd-user-profile-api:
    image: hmcts/ccd-user-profile-api
    environment:
      USER_PROFILE_DB_HOST: ccd-user-profile-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME:
      USER_PROFILE_DB_PASSWORD:
      USER_PROFILE_DB_USE_SSL:
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,sscs
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ccd-user-profile-database
    links:
      - ccd-user-profile-database
      - service-auth-provider-api

  ccd-user-profile-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      USER_PROFILE_DB_USERNAME:
      USER_PROFILE_DB_PASSWORD:
    ports:
      - 5453:5432
    volumes:
      - ccd-user-profile-database-data:/var/lib/postgresql/data

  ccd-definition-store-api:
    image: hmcts/ccd-definition-store-api
    environment:
      DEFINITION_STORE_DB_HOST: ccd-definition-store-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME:
      DEFINITION_STORE_DB_PASSWORD:
      DEFINITION_STORE_DB_USE_SSL:
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,sscs
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4451:4451
    depends_on:
      - ccd-definition-store-database
      - ccd-user-profile-api
    links:
      - ccd-definition-store-database
      - ccd-user-profile-api
      - idam-api
      - service-auth-provider-api

  ccd-definition-store-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DEFINITION_STORE_DB_USERNAME:
      DEFINITION_STORE_DB_PASSWORD:
    ports:
      - 5451:5432
    volumes:
      - ccd-definition-store-database-data:/var/lib/postgresql/data

  ccd-data-store-api:
    image: hmcts/ccd-data-store-api
    environment:
      DATA_STORE_DB_HOST: ccd-data-store-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME:
      DATA_STORE_DB_PASSWORD:
      DATA_STORE_DB_USE_SSL:
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,sscs
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4452:4452
    depends_on:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
    links:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - idam-api
      - service-auth-provider-api

  ccd-data-store-database:
    image: "docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-database:${BRANCH:-master}"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DATA_STORE_DB_USERNAME:
      DATA_STORE_DB_PASSWORD:
    ports:
      - 5452:5432
    volumes:
      - ccd-data-store-database-data:/var/lib/postgresql/data

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      IDAM_SUPERUSER_EMAIL: ccd@hmcts.net
      SPRING_DATASOURCE_URL: jdbc:postgresql://idam-database:5432/idam
      SPRING_MAIL_HOST: smtp-server
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      NOTIFY_API_KEY: AAAAAAAAAAAAAAAA
      NOTIFY_CMC_ACTIVATE_USER_TEMPLATE: 76aa8695-64e8-4afd-ae13-bc8385302b1f
      IDAM_SECRET: idam_test_secret
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_CCD_WHITELIST: http://localhost:3451/oauth2redirect
      NOTIFY: "false"
      NOTIFY_CMC_WELCOME_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE: fake
      NOTIFY_SSCS_WELCOME_USER_TEMPLATE: fake
      NOTIFY_RESET_PASSWORD_TEMPLATE: "${NOTIFY_RESET_PASSWORD_TEMPLATE:fake}"
      NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_CCD_ACTIVATE_USER_TEMPLATE: fake
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
      http_proxy:
      https_proxy:
      no_proxy:
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_SSCS: QM5RQQ53LZFOSIXJ
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: DEBUG
    ports:
      - 4501:8080
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server
  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest
    ports:
      - 5501:5432
    volumes:
      - idam-database:/var/lib/postgresql/data

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      AUTH_PROVIDER_SERVICE_SERVER_JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      AUTH_PROVIDER_SERVICE_TESTING_SUPPORT_ENABLED: "true"
      AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_SSCS: "${IDAM_KEY_CCD_GATEWAY}"

  smtp-server:
    image: mailhog/mailhog

  ccd-case-management-web:
    image: "hmcts/ccd-case-management-web"
    container_name: ccd-case-management-web
    environment:
      IDAM_LOGIN_URL: https://localhost:3501/login
      CCD_GATEWAY_BASE_URL: http://localhost:3453
      CCD_ACTIVITY_BASE_URL:
      DM_GATEWAY_BASE_URL: https://api-gateway.dev.dm.reform.hmcts.net
      OAUTH2_CLIENT_ID: ccd_gateway
    ports:
      - 3451:3451
    depends_on:
      - ccd-api-gateway

  ccd-api-gateway:
    image: "hmcts/ccd-api-gateway"
    container_name: ccd-api-gateway
    environment:
      IDAM_LOGOUT_URL: https://localhost:3501/login/logout
      IDAM_BASE_URL: http://idam-api:8080
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_OAUTH2_TOKEN_ENDPOINT: http://idam-api:8080/oauth2/token
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api

  authentication-web:
    image: docker.artifactory.reform.hmcts.net/auth/authentication-web:latest
    environment:
     IDAM_API_URL: http://idam-api:8080
     IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS: "false"
     REFORM_SERVICE_NAME: idam-api
     REFORM_TEAM: idam
     REFORM_ENVIRONMENT: local
    ports:
      - 3501:8000
    links:
      - idam-api
    depends_on:
      - idam-api

  sscs-case-loader:
      build:
        context: .
        args:
          - http_proxy
          - https_proxy
          - no_proxy=service-auth-provider-api,idam-api,ccd-data-store-api
#      image: docker.artifactory.reform.hmcts.net/reform/sscs-case-loader
      environment:
        # these environment variables are used by java-logging library
        - ROOT_APPENDER
        - JSON_CONSOLE_PRETTY_PRINT=yes
        - ROOT_LOGGING_LEVEL=info
        - REFORM_SERVICE_NAME=sscs-case-loader
        - REFORM_TEAM=sscs
        - REFORM_ENVIRONMENT=local
        - GAPS2_SFTP_HOST=sscs-sftp
        - GAPS2_SFTP_USER=sftp
        - GAPS2_SFTP_DIR=incoming
        - GAPS2_SFTP_PORT=22
        - http_proxy=
        - https_proxy=
        - no_proxy=
        - IGNORE_CASES_BEFORE_DATE=1901-01-01
        - CORE_CASE_DATA_API_URL=http://ccd-data-store-api:4452
        - CORE_CASE_DATA_USER_ID=16
        - CORE_CASE_DATA_JURISDICTION_ID=SSCS
        - CORE_CASE_DATA_CASE_TYPE_ID=Benefit
        - IDAM_URL=http://idam-api:8080
        - IDAM_S2S_AUTH_TOTP_SECRET=AAAAAAAAAAAAAAAC
        - IDAM_S2S_AUTH_MICROSERVICE=sscs
        - IDAM_S2S_AUTH=http://service-auth-provider-api:8080
        - IDAM_SSCS_SYSTEMUPDATE_USER=SSCS_SYSTEM_UPDATE
        - IDAM_SSCS_SYSTEMUPDATE_PASSWORD=SSCS_SYSTEM_UPDATE
        - IDAM_OAUTH2_CLIENT_ID=sscs
        - IDAM_OAUTH2_CLIENT_SECRET=QM5RQQ53LZFOSIXJ
        - GAPS2_KEY_LOCATION = ${GAPS2_KEY_LOCATION}
      depends_on:
        - gaps2-sftp
        - ccd-data-store-api
      links:
        - gaps2-sftp
        - ccd-data-store-api
        - idam-api
        - service-auth-provider-api
      ports:
        # check .env
        - $SERVER_PORT:$SERVER_PORT
      healthcheck:
        retries: 10


  gaps2-sftp:
      build:
        context: docker/sftp
      #image: docker.artifactory.reform.hmcts.net/sscs/sscs-sftp:${SSCS_TESTS_VERSION:-latest}
      container_name: sscs-sftp
      command: sftp:pass:1001
      healthcheck:
        retries: 40
      ports:
        - "2222:22"
      volumes:
        - ./docker/sftp/data/incoming:/home/sftp/incoming

volumes:
  ccd-user-profile-database-data:
  ccd-definition-store-database-data:
  ccd-data-store-database-data:
  idam-database:
