server.port: ${PORT:8082}

management.security.enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

sscs.gaps2:
  schema.location:
    delta: /schema/SSCS_Extract_Schema_0.8.xsd
    reference: /schema/SSCS_Extract_Schema_Reference_0.2.xsd
