server:
  port: ${SSCS_CASE_LOADER_PORT:8082}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  userId: ${CORE_CASE_DATA_USER_ID:19}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  eventId: ${CORE_CASE_DATA_EVENT_ID:appealCreated}

idam:
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:ccd_gw}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}



