server.port: ${PORT:8083}

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  config:
    import: "optional:configtree:/mnt/secrets/sscs/"
core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}

idam:
  url: ${IDAM_URL:http://localhost:5062}
  s2s-auth:
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
    url: ${IDAM_S2S_AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}
    jwkUrl: ${IDAM_API_JWK_URL:http://localhost:5062/jwks}
  api:
    url: ${IDAM_URL:http://localhost:5062}
  client:
    id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
    secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirect_uri: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}

management:
  info.git.mode: full
  endpoints.web.base-path: /
  endpoint.health.show-details: always

sftp:
  keyLocation:  ${GAPS2_KEY_LOCATION}
  host: ${GAPS2_SFTP_HOST:localhost}
  port: ${GAPS2_SFTP_PORT:2222}
  username: ${GAPS2_SFTP_USER:sftp}
  inputDirectory: ${GAPS2_SFTP_DIR:incoming}

spring.application.name: CaseLoader Insights WebApp

sscs.case.loader:
  ignoreCasesBeforeDate: ${IGNORE_CASES_BEFORE_DATE:1017-07-01}
  ignoreHearingPostponedBeforeDate: ${IGNORE_HEARING_POSTPONED_BEFORE_DATE:2020-12-07}
  shutdown.delay.time: 7
  processMinorEvents: ${PROCESS_MINOR_EVENTS:true}
  useExistingDate: ${USE_EXISTING_DATE:true}
  startHour: ${CASE_LOADER_START_HOUR:21}
  endHour: ${CASE_LOADER_END_HOUR:7}

logging.level:
  org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
  uk.gov.hmcts.reform.sscs: ${LOG_LEVEL_SSCS:INFO}
  uk.gov.hmcts.fortifyclient: INFO

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding
spring.main.allow-bean-definition-overriding: true

judicial-ref.api.url: ${JUDICIAL_REF_API_URL:http://localhost:5555}
ccd-callback-orchestrator.api.url: ${CCD_CALLBACK_ORCHESTRATOR_API_URL:http://localhost:8070}

features:
  data-migration:
    interpreter: ${INTERPRETER_DATA_MIGRATION_ENABLED:false}
    rollback: ${DATA_MIGRATION_ROLLBACK:false}
    encoded-data-string: ${ENCODED_MIGRATION_DATA_STRING:W3sicmVmZXJlbmNlIjoiMTcwMzAyMTkyNDYwMDQxOCIsImludGVycHJldGVyIjoiIFllcyIsInN0YXRlIjoiIHJlYWR5VG9MaXN0ICAgICAgIiwiZXhpc3RpbmdfbGFuZ3VhZ2VfdmFsdWUiOiIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiLCJtYXBwZWRfbGFuZ3VhZ2VfdmFsdWUiOiJiZW5nYWxpIn1d}
  case-loader-update-caseV2:
      enabled: ${CASE_LOADER_UPDATE_CASE_V2_ENABLED:false}
