server.port: ${PORT:8082}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  userId: ${CORE_CASE_DATA_USER_ID:16}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  eventId: ${CORE_CASE_DATA_EVENT_ID:appealCreated}

idam:
  url: ${IDAM_URL:http://localhost:4501}
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:SSCS_SYSTEM_UPDATE}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:http://localhost}

management.security.enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

sftp:
  keyLocation: ${GAPS2_KEY_LOCATION:./docker/sftp-docker}
  host: ${GAPS2_SFTP_HOST:localhost}
  port: ${GAPS2_SFTP_PORT:2222}
  username: ${GAPS2_SFTP_USER:sftp}
  inputDirectory: ${GAPS2_SFTP_DIR:incoming}

sscs.gaps2.schema.location:
  delta: /schema/SSCS_Extract_Schema_0.8.xsd
  reference: /schema/SSCS_Extract_Schema_Reference_0.2.xsd
