server.port: ${PORT:8082}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  userId: ${CORE_CASE_DATA_USER_ID:16}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}

idam:
  url: ${IDAM_URL:http://localhost:4501}
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:SSCS_SYSTEM_UPDATE}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_SSCS_URL:https://localhost:9000/poc}

management.security.enabled: ${MANAGEMENT_SECURITY_ENABLED:false}

sftp:
  keyLocation: ${GAPS2_KEY_LOCATION:./docker/sftp-docker}
  host: ${GAPS2_SFTP_HOST:localhost}
  port: ${GAPS2_SFTP_PORT:2222}
  username: ${GAPS2_SFTP_USER:sftp}
  inputDirectory: ${GAPS2_SFTP_DIR:incoming}

spring.application.name: CaseLoader Insights WebApp

sscs.case.loader:
  cron.schedule: ${SSCS_CASE_LOADER_CRON_SCHEDULE:0 0/5 * * * ?}
  ignoreCasesBeforeDate: ${IGNORE_CASES_BEFORE_DATE:1017-07-01}
  url: ${SSCS_CASE_LOADER_URL:http://localhost:8082}

logging.level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    uk.gov.hmcts.reform.sscs: ${LOG_LEVEL_SSCS:INFO}

---
spring:
    profiles: development

scheduling.enabled: false
