server.port: ${PORT:8082}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  userId: ${CORE_CASE_DATA_USER_ID:19}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  eventId: ${CORE_CASE_DATA_EVENT_ID:appealCreated}

idam:
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:ccd_gw}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  url: ${IDAM_URL:http://localhost:4501}
  role:
    email: ${IDAM_ROLE_EMAIL:david.crespo@hmcts.net}
    password: ${IDAM_ROLE_PASSWORD:password}

management.security.enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

sftp:
  keyLocation: ${GAPS2_KEY_LOCATION:./docker/sftp-docker}
  host: ${GAPS2_SFTP_HOST:localhost}
  port: ${GAPS2_SFTP_PORT:2222}
  username: ${GAPS2_SFTP_USER:sftp}
  inputDirectory: ${GAPS2_SFTP_DIR:incoming}

sscs.gaps2.schema.location:
  delta: /schema/SSCS_Extract_Schema_0.8.xsd
  reference: /schema/SSCS_Extract_Schema_Reference_0.2.xsd




