sftp:
  keyLocation:  ${GAPS2_KEY_LOCATION}

logging.level:
  org.springframework.web: ${LOG_LEVEL_SPRING_WEB:debug}
  uk.gov.hmcts.reform.sscs: ${LOG_LEVEL_SSCS:debug}
  uk.gov.hmcts.reform.sscs.idam.IdamApiClient: DEBUG
  uk.gov.hmcts.reform.ccd.client.CoreCaseDataApi: DEBUG

feign:
  client:
    config:
      idam-api:
        loggerLevel: full
      core-case-data-api:
        loggerLevel: full


sscs.case.loader.shutdown.delay.time: 1
