package uk.gov.hmcts.reform.sscs.refdata.domain;

import static uk.gov.hmcts.reform.sscs.refdata.domain.RefKeyField.*;

public enum RefKey {
    APPEAL_STATUS(APPEAL_STATUS_ID),
    CASE_CODE(CASE_CODE_ID),
    BUSINESS_RULES_GROUP(BUSINESS_RULES_GRP_ID),
    TRIBUNAL(TRIBUNAL_ID),
    TRIBUNAL_TYPE(TRIBUNAL_TYPE_ID),
    OFFICE(OFFICE_ID),
    BEN_ASSESS_TYPE(BEN_ASSESS_TYPE_ID),
    ADMIN_TEAM(ADMIN_TEAM_ID),
    VENUE(VENUE_ID),
    DISTRICT(DISTRICT_ID),
    ITS_CENTRE(ITS_CENTRE_ID),
    PTTP_ROLE(PTTP_ROLE_ID),
    SEPARATE_CORRESPONDENCE(SEPARATE_CORRESPONDENCE_ID),
    LANGUAGE_TYPE(LANGUAGE_TYPE_ID),
    FUR_EVID_TYPE(FUR_EVID_TYPE_ID),
    HEARING_OUTCOME(HEARING_OUTCOME_ID),
    POSTPONE_REASON(POSTPONE_REASON_ID),
    BAT_CODE_MAP(BAT_CODE);

    public final RefKeyField keyField;

    RefKey(RefKeyField caseCodeId) {

        keyField = caseCodeId;
    }
}
