apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - image: ${IMAGE_NAME}
        name: ${SERVICE_NAME}
        ports:
          - containerPort: 8082
        env:
          - name: CORE_CASE_DATA_API_URL
            value: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
          - name: CORE_CASE_DATA_JURISDICTION_ID
            value: "SSCS"
          - name: CORE_CASE_DATA_CASE_TYPE_ID
            value: "Benefit"
          - name: IDAM_URL
            value: "${IDAM_URL}"
          - name: IDAM.S2S-AUTH.TOTP_SECRET
            value: "${IDAM_S2S_AUTH_TOTP_SECRET}"
          - name: IDAM.S2S-AUTH
            value: "${IDAM_S2S_AUTH}"
          - name: IDAM.S2S-AUTH.MICROSERVICE
            value: "${IDAM_S2S_AUTH_MICROSERVICE}"
          - name: IDAM_SSCS_SYSTEMUPDATE_USER
            value: "${IDAM_SSCS_SYSTEMUPDATE_USER}"
          - name: IDAM_SSCS_SYSTEMUPDATE_PASSWORD
            value: "${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}"
          - name: IDAM_OAUTH2_CLIENT_ID
            value: "sscs"
          - name: IDAM_OAUTH2_CLIENT_SECRET
            value: "${IDAM_OAUTH2_CLIENT_SECRET}"
          - name: IDAM_OAUTH2_REDIRECT_URL
            value: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
          - name: GAPS2_KEY_LOCATION
            value: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpgIBAAKCAQEAuB64U0n99/0/IuJM3SeiQaNLnWCKy+qMy+06D9UkpOrLHXpl\n6DkEQsTEZ58Xs00j+T/xlf6wfyl2qJn9B/ZtkdGeGAsdrmGtGQZ6tQLTPP1f0q7P\nDC568Rno5Y3r780VYC6+QQcLSgC5E+45jW52CS3sJuZTJ+4vt6huG+m5MbKMPOVe\n/QKnb20gNRsOGoX8oIHlbcogX62huUbAKgB9/eSj8kBSh1il19Xu6/WpBYORIZZM\n0Bh5DDQIMULNc965X9BlO50N15er3fftfIjv1pl91i4E1v/Rv6W5qIM3rgzLEjP2\n6n0+Lbhgpfc7yR/GoycUHJQrtd2PDKPjcv052wIDAQABAoIBAQCVxD9RWKWiXDhI\nKuY1GrEsTSULveUI3CBtHOmWyVzGXUqdDtvoGsDxgtb0JwADVGNHsxDTXtm4hkTD\n/oZJPNWBwI2lpx0cpM1FxvR3WvXy7XNNj+5RTVmp1taQK3JYnGyf0UXm5VD0gEQM\nB0J/XfPboaQvPDk2CNR9wx7Vy7ddySnyc0q9QEDo+Hb30QiacZDvvM2H08AXgegm\nFJTgR0xOgTncz/2Iw0xNL5rUA2+xnFvMeBqfOMLvSSvtTbwr4BQbup3r9uc5BYFC\n4NASRRh7ZLjzzAE2IOrv64/j0kjhSTliEsxLuhaVZgbhFVKuMW3ZwbG+7VVfY5ra\nIbErIPZZAoGBAOWeXHMGwzq8fPTKaHRRRpZ0Kk3DOWaLh2GuYn+XbjbfJTximzD9\nTgFXUhKau8wsvQ3t2udc9BbWX1mTFKUo/JJJPzp6HVHRSCozk4KFB3zdT2Lz45yA\n8jxaJFkGYiszpv+5tKU//cEHPr4pA+w7CPMk7RCe2VUkEXSHYXPA18TlAoGBAM1G\nIo1xTJO4cwPje3vlHmbEaNrjnTAere7T9LH1Lv1dPGxKhKlnbGLVo6CFsYjhV6DB\nbkSSiXlLT3uSuBakO1WRya0TLiYup7PCnTkjjivbFSxxbMqMxzi4RMx6pQde4qhd\nd3wf3JjY1JPIgw5OINVtbkTHW01LoLW4EaKPwde/AoGBAMPzuQGQq9rcL+bXNPzO\nv2Z2DAQArmOMfyQlJXmtSSkalTRLEhVklcUfN7MYyVscctoIOd9nvAYhO429rsij\niadtSsAkphDEgMlC6odf71vnoW/Yok1U3WQTqSEwCWbE1ac2W6sKSQsJm8m8RtS6\nLJES2hxs8xtthFflkIyv7XLhAoGBAJZpHqZPb5IKJFSkGfZFg0o//qjtAV+iC0al\njnXbNyw1ZjHfRGewva2J51SWweiPXZsQQRED4rG66imc70C/5C4mHgWwuS8HHqDM\nKFIW6HTgGhqvncyo7M110AuYjlXhQ+mkWwnbetOQhesnkEgqHUrl3VeOUCtKEB83\nGczo01uXAoGBAIx3md2Bpj2q1320y6HDkfiTeBHBiO0lAmRUlxBYDD8j38voXgbc\nfVIJ9ZmQlS1z1kvWUf1hVR3DGFj+81i6mdfQvwIBrHVqjY21gXH4QnsMUd/f9K/V\njExsyE94Udj65VZ9Jky5WEnEmicFE7JPaZm8Mnb67rMur93siXQ3oyL+\n-----END RSA PRIVATE KEY-----\n"
          - name: GAPS2_SFTP_HOST
            value: "localhost"
          - name: GAPS2_SFTP_PORT
            value: "22"
          - name: GAPS2_SFTP_USER
            value: "sftp"
          - name: GAPS2_SFTP_DIR
            value: "incoming"
          - name: SSCS_CASE_LOADER_CRON_SCHEDULE
            value: "0 0/5 * * * ?"
          - name: IGNORE_CASES_BEFORE_DATE
            value: "2088-01-01"
          - name: ROOT_LOGGING_LEVEL
            value: "INFO"
          - name: LOG_LEVEL_SPRING_WEB
            value: "INFO"
          - name: LOG_LEVEL_SSCS
            value: "INFO"
          - name: DEMO_TEST
            value: "Testing Demo for update config"

        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "2500m"

        readinessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: /health
            port: 8082

      - image: hmcts/sscs-sftp
        name: sftp
        args:
          - "sftp:pass:1001"
        ports:
          - containerPort: 22

        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8082
  selector:
    app: ${SERVICE_NAME}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: ${SERVICE_FQDN}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${SERVICE_NAME}
          servicePort: 80
---
