root_logging_level = "DEBUG"
log_level_spring_web = "DEBUG"
log_level_sscs = "DEBUG"
management_security_enabled = "false"
infrastructure_env = "test"
gaps2_sftp_user = "sscs-sftp-test"
core_case_data_user_id = "43132"
ignore_cases_before_date = "2017-01-01"
