management_security_enabled = "false"
infrastructure_env = "preprod"
gaps2_sftp_user = "sftp-aat"
ignore_cases_before_date = "1970-01-01"
sftp_key_location = "sftp_key_aat"
idam_redirect_url = "https://sscs-case-loader-aat.service.core-compute-aat.internal"
gaps2_sftp_dir = "/incoming"
