management_security_enabled = "false"
infrastructure_env = "preprod"
gaps2_sftp_user = "sscs-sftp-demo"
ignore_cases_before_date = "2099-01-01"
sftp_key_location = "sftp_key_demo"
idam_redirect_url = "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
