management_security_enabled = "false"
infrastructure_env = "preprod"
gaps2_sftp_user = "sscs-sftp-test"
core_case_data_user_id = "506"
ignore_cases_before_date = "2099-01-01"
sftp_key_location = "sftp_key_test"
sscs_case_loader_cron_schedule = "0 0 23 31 DEC ? 2009"