infrastructure_env = "prod"
gaps2_sftp_user = "sscs-sftp-prod"
sscs_case_loader_cron_schedule = "0 0 * * * *"
ignore_cases_before_date = "2018-07-26"
sftp_key_location = "gaps2_service_sftp_key"
idam_redirect_url = "https://sscs-case-loader-prod.service.core-compute-prod.internal"
