infrastructure_env = "prod"
gaps2_sftp_user = "sscs-sftp-prod"
ignore_cases_before_date = "2018-07-26"
sftp_key_location = "gaps2_service_sftp_key"
idam_redirect_url = "https://sscs-case-loader-prod.service.core-compute-prod.internal"
