infrastructure_env = "prod"
gaps2_sftp_user = "sscs-sftp-prod"
sscs_case_loader_cron_schedule = "0 0 09-16/1 * * MON-FRI"
ignore_cases_before_date = "2018-07-01"
core_case_data_user_id = "11289"
sftp_key_location = "gaps2_service_sftp_key"
